### PR TITLE
Update prompt to fix wrong language in response

### PR DESCRIPTION
**Pull request by olivernybo**
Fixes issue #16 / #33

### CODE REVIEW

**Review by Myzel394 — CHANGES_REQUESTED** [review]
Please also update
```python
        yield "参考资料:\n"
```

on line 185

**Comment by olivernybo** [comment]
It seems the author has resolved this themself, hence why I closed the pull request.

**Comment by Myzel394** [comment]
are you sure? just checked the repo, it still seems to be in Chinese https://github.com/nashsu/FreeAskInternet/blob/main/free_ask_internet.py#L123

**Comment by arsaboo** [comment]
I've tested this and it still returns results in Chinese occasionally.

**Pull request closed without merging**
